### ISSUE TITLE
OBC 2018 todo

### ISSUE THREAD

**Issue by tridge** [CanberraUAV/cuav#41]
Some things that need doing:

- [x] fix RGB <-> BGR on map
- [x] add lidar based height to mav_position.py
- [x] only send ADSB_VEHICLE msgs if they are close enough to a vehicle
- [x] send ADSB_VEHICLE msgs to both relay and retrieval vehicle
- [x] delay takeoff if DNFZ blocking path
- [x] can't measure distances in images in camera_air
- [x] brightness control broken in mosaic
- [ ] fix rcout set_failsafe_pwm on ChibiOS
- [x] place marker not working in camera_air
- [x] image fetched marker not showing on map
- [x] show image from map not working in camera_air
- [x] disable SBUS failsafe handling parameter
- [x] scale obstacle margin for obstacle speed and turn rate
- [x] prevent pkts from 3G on porter from coming back down the rfd900x link
- [x] send ADSB_VEHICLE pkts over all 3 links
- [x] work up a list of OS configuration changes required on laptops which are to be "hands-off" (screensavers, automatic updates, crash-catching tools like whoopsie, ...)
- [x] in search area WP_MAX_RADIUS should be zero. In main area should be 50
- [ ] add LZ exclusion areas for trees
- [ ] add method to reset battery state
- [ ] wp list gets stuck on companion
- [x] look at bunny hop landing from 30th august
- [ ] allow ALT_OFFSET in terrain following mode
- [ ] cope with dual-aircraft NMEA
- [x] adjust cuav_check parameter checking
- [ ] use USER WPs for AFS targets
- [x] check GEOID for asterix data
- [x] check GEOID for NMEA

From all-up test 2018-09-10:
- [x] Kraken needs to get obstacle data.  tridge's laptop will need to relay asterix data to Stephen's laptop as well as send it to vehicle; Stephen's needs to display but not process further
- [ ] fence auto-enable activated too late on Kraken; activated at WP1, should have been active earlier
- [x] altitude is being read out too often (fix in mavinit scripts on both groundstations)
- [x] Kraken struggled to reach altitude - review dataflash log
- [x] motors were spinning when vehicle was still in `NAV_WAIT_AIRSPACE`
- [x] Porter had no obstacles but did not pass through `NAV_WAIT_AIRSPACE`
- [x] vehicles may be sending ADSB packets to ground - stop that!
- [ ] Optus Pi dead (doesn't ping)
- [ ] check for compass failure on Kraken
- [ ] need to fit df13 to USB externder to Porter (get from Ranger?)
- [x] display collision data on ground while disarmed
- [ ] need another all-up test using quadstar and the Ranger
- [ ] need to make sure airspeed calibration is done!
- [ ] GREG: pull-ring on e-stop
- [ ] GREG: file down connector
- [ ] GREG: safety pin for GPS
- [ ] check scheduling on Porter
- [x] log counts of objects currently being held for avoidance
- [ ] add into list of things to consider when plotting mission: choose first waypoint to avoid trees!
- [ ] add minimum flight time for Porter; full-fuel-loadout makes for hard second-takeoffs!
- [ ] DF-13 extender for Pixhawk in Porter (steal from Ranger?)
- [ ] add 5-second skies-are-clear-so-I'm-going message
- [ ] check data rates on GCS
- [ ] check why secondary links from Porter weren't helping links be non-claggy
- [ ] turn off IMU batch sample logging
- [x] PETER: work out why mavlinklogdump won't write ISBD packets
- [x] fix no-obstacles-on-Kraken issue
- [ ] add to checklist: turn camera on on Kraken
- [x] ensure alt readout rates are correct for feet in mavinit.scr
- [x] set numcells for Kraken in mavinit.scr
- [ ] consider motor stopping on descent at far site
- [ ] sudden drop after levelling off in takeoff
- [ ] ensure thermal throttling is off in ESCs.
- [ ] get to bottom of erratic avoidance
- [ ] look at Leonard's PR to aid in climb-out at remote site (prioritize climb vs yaw)
- [ ] consider getting HIL working
- [ ] improve filtering on GCS for obstacles
- [x] use SITL to reproduce avoidance issues (erratic aircraft)
- [ ] AVDM doesn't do fence-avoidance logging

**Comment by stephendade** [comment]
Turns out georeferencing is actually done on the air side, so that saves a tonne of work :)
